College/urls.py
from django.contrib import admin
from django.urls import path, include
from myscheduleApp import views
from Activity import views as views_activity
from accordion import views as views_accordion
from BooksLib import views as views_bookslib
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myscheduleApp.urls')),
    path('addnew', views.addnew),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
    path('activity', views_activity.activity),
    path('add/<int:id>', views_activity.add),
    path('deleteact/<int:id>', views_activity.delete),
    path('addact', views_activity.addact),
    path('accordion', views_accordion.accordion),
    path('bookslib', views_bookslib.bookslib),
    path('data', views_bookslib.parseData),
]

myscheduleApp/urls.py
from django.urls import path

from . import views

app_name = 'myscheduleApp'

urlpatterns = [
    path('', views.index),
]

Activity/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
	activity = models.CharField(max_length=50)

	class Meta:
		db_table = 'Activities'
		ordering = ['activity']
	
	def __str__(self):
		return self.activity

class Person(models.Model):
	 name = models.CharField(max_length=25)
	 activities = models.ManyToManyField(Activity)

	 class Meta:
	 	db_table = 'Persons'

	 def __str__(self):
	 	return self.name

BooksLib/models.py
from django.db import models

# Create your models here.

accordion/models.py
from django.db import models

# Create your models here.

myscheduleApp/models.py
from django.db import models

# Create your models here.
class MataKuliah(models.Model):
	nama_matkul = models.CharField(max_length=25)
	dosen = models.CharField(max_length=25)
	sks = models.CharField(max_length=25)
	deskripsi = models.CharField(max_length=25)
	term = models.CharField(max_length=25)
	ruang_kelas = models.CharField(max_length=25)

	class Meta:
		db_table = "matakuliah"
	def __str__(self):
		return self.nama_matkul

Activity/forms.py
from django import forms
from .models import Activity, Person

class ActivityForm(forms.ModelForm):
	class Meta:
		model = Activity
		fields = ('activity',)

		widgets ={
			'activity':forms.TextInput(attrs={'class':'form-control', 'placeholder' : 'Activity'}),
			
		}
class PersonForm(forms.ModelForm):
	class Meta:
		model = Person
		fields = ('name',)

		widgets ={
			'name':forms.TextInput(attrs={'class':'form-control', 'placeholder' : 'Name'}),
			
		}

myscheduleApp/forms.py
from django import forms
from .models import MataKuliah

class Subject(forms.ModelForm):
	class Meta:
		model = MataKuliah
		fields = '__all__'

		widgets ={
			'nama_matkul':forms.TextInput(attrs={'class':'form-control', 'placeholder' : 'Nama Matkul'}),
			'dosen':forms.TextInput(attrs={'class':'form-control', 'placeholder' : 'Dosen'}),
			'sks':forms.TextInput(attrs={'class':'form-control', 'placeholder' : 'Jumlah SKS'}),
			'deskripsi':forms.Textarea(attrs={'class':'form-control', 'placeholder' : 'Write Subject Description Here'}),
			'term':forms.TextInput(attrs={'class':'form-control', 'placeholder' : 'e.g Gasal 2019/2020'}),
			'ruang_kelas':forms.TextInput(attrs={'class':'form-control', 'placeholder' : 'Ruang Kelas'}),
		}

Activity/views.py
from django.shortcuts import render, redirect
from .models import Activity, Person
from .forms import PersonForm, ActivityForm

# Create your views here.
def activity(request):
	activity = Activity.objects.all()
	form = PersonForm()
	form_act = ActivityForm()
	context ={
		'activities':activity,
		'form':form,
		'form_act':form_act,
	}
	return render(request, 'activity.html',context)

def add(request, id):
	if request.method == "POST":
		form=PersonForm(request.POST)
		if form.is_valid():
			person = Person(name=form.cleaned_data['name'])
			person.save()
			person.activities.add(Activity.objects.get(id=id))
			return redirect('/activity')
	else:
		form=PersonForm()
	return render(request, 'activity.html')

def delete(request, id):
	Person.objects.filter(activities=Activity.objects.get(id=id)).delete()
	Activity.objects.get(id=id).delete()
	return redirect('/activity')

def addact(request):
	if request.method == "POST":
		form = ActivityForm(request.POST)
		if form.is_valid():
			activity = Activity(activity=form.cleaned_data['activity'])
			activity.save()
			return redirect('/activity')
	else:
		form = ActivityForm()
	return render(request, 'activity.html')

BooksLib/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json
# Create your views here.
def bookslib(request):
	context = {}
	return render(request, 'booksLib.html', context)
def parseData(request):
	keyword = request.GET['q']
	url = 'https://www.googleapis.com/books/v1/volumes?q=%s' %keyword
	request_data = requests.get(url)
	data = json.loads(request_data.content)
	return JsonResponse(data, safe=False)

accordion/views.py
from django.shortcuts import render

# Create your views here.
def accordion(request):
	return render(request,'accordion.html')

myscheduleApp/views.py
from django.shortcuts import render, redirect
from .models import MataKuliah
from .forms import Subject
from Activity.models import Activity, Person
# Create your views here.
def index(request):
	matkul = MataKuliah.objects.all()
	activity = Activity.objects.all()
	return render(request, 'home.html', {'matkul': matkul, 'activities':activity})
	
def addnew(request):
	if request.method == "POST":
		form = Subject(request.POST)
		if form.is_valid():
			try:
				form.save()
				return redirect('/')
			except:
				pass
	else:
		form = Subject()
	return render (request,'add.html',{'form':form})

def edit(request, id):
	matkul = MataKuliah.objects.get(id=id)
	return render(request, 'edit.html', {'matkul': matkul})

def update(request, id):
	matkul = MataKuliah.objects.get(id=id)
	form = Subject(request.POST or None, instance=matkul)
	if form.is_valid():
		form.save()
		return redirect('/')
	else:
		matkul = MataKuliah.objects.get(id=id)
		return render (request, 'edit.html',{'matkul':matkul})


def destroy(request, id):
	matkul = MataKuliah.objects.get(id=id)
	matkul.delete()
	return redirect('/')

Activity/templates/activity.html
{% extends 'base.html' %}
{% load static %}
{% block title %}My Activity{% endblock title %}
{% block content %}
<div id="actcontainer" class="container mt-5">
	<div class="page-header">
		<h2 class="text text-center text-info display-1">Join Me</h2>
	</div>
	<div class="jumbotron">
		{% if activities.count == 0%}
			<h3 class="text-success">Ooops!! No Activity yet..</h3>
		{% endif %}
		<div id="actcarddeck" class="card-deck">
			{% for act in activities %}
				<div id="actcard" class="card">
						<div class="card-header">
							<h5 class="text-center" style="color:black">{{ act }}</h5>
						</div>
					<div id="actcardbody" class="card-body">
						<ol id="actcardol">
				{% for person in act.person_set.all %}
							<li class="card-text">{{ person }}</li>	
				{% endfor %}
						</ol>
					</div>
					<div class="card-footer">
						<div class="row">
							<div class="col">
								<a href="/deleteact/{{ act.id }}" class="btn btn-danger btn-xs" data-title="Delete" onclick="return confirm('Are you sure you want to delete {{ act }}?')"><span class="fas fa-trash fa-sm"></span></a>
							</div>
							<div class="col">
								<div class="dropdown">
									<span class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="false" aria-expanded="false">
									   Add Participant
									</span>
									<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
										<form class="post-form dropdown-item" method="POST" action="/add/{{act.id}}" autocomplete="off">
										    {% csrf_token %}
										    {{form}}
										    <button class="btn btn-success btn-sm" type="submit" value="submit"><i class="fas fa-sign-in-alt"></i> Submit</button>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				
			{% endfor %}
		</div>
		<div class="dropdown">
			<span class="btn btn-primary dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="false" aria-expanded="false">
			   Add Activity
			</span>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
				<form class="post-form dropdown-item" method="POST" action="/addact" autocomplete="off">
				    {% csrf_token %}
				    {{form_act}}
				    <button class="btn btn-success btn-sm" type="submit" value="submit"><i class="fas fa-sign-in-alt"></i> Submit</button>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

BooksLib/templates/booksLib.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Books Corner{% endblock title %}

{% block content %}
<div class="container mt-5" id="container_input">
	<h2 class="text text-center display-3" style="color:white;">Find A Book</h2>
	<input id="keyword" type="text" placeholder="Search" class="input">
	
</div>
<div class="container mt-5" id="container_books">
	<div class="table-responsive">
		<table id="show" class="table table-striped table-dark table-hover table-bordered">
			
		</table>
	</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
	$("#keyword").keyup(function(){
		let search_key = $("#keyword").val();
		let url_source = "/data?q=" + search_key;
		$.ajax({
			url : url_source,
			success : function(show){
				let dataToShow = $("#show");
				dataToShow.empty();
				for(i=0; i<show.items.length; i++){
					let title = show.items[i].volumeInfo.title;
					let author = show.items[i].volumeInfo.authors;
					let publisher = show.items[i].volumeInfo.publisher;
					let publishedDate = show.items[i].volumeInfo.publishedDate;
					let ISBN = show.items[i].volumeInfo.industryIdentifiers[1].identifier;
					let image = show.items[i].volumeInfo.imageLinks.smallThumbnail;
					dataToShow.append('<tr><td><img src=' + image + '></td><td><ul><li>Title &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: ' + title + '</li><li>Author &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: ' + author + '</li><li>Publisher &nbsp;: ' + publisher + '</li><li>Year &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: ' + publishedDate + '</li><li>ISBN &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: ' + ISBN + '</li></ul></td></tr>');
				}
			}
		});
	});
</script>
{% endblock %}

accordion/templates/accordion.html
{% extends 'base.html' %}
{% load static %}
{% block title %}My First Accordion{% endblock title %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/jquery-3.5.1.js' %}"></script>
<script>
	document.querySelectorAll('.accordion_header').foreach(button =>{
		button.addEventListener('click', ()=>{
			const accordionBody = button.nextElementSibling;

			button.classList.toggle('.accordion_header--active');

			if(button.classList.contains('.accordion_header--active')){
				accordionBody.style.maxHeight = accordionBody.scrollHeight + 'px';
			}
			else{
				accordionBody.style.maxHeight =0;
			}
		})
	})
</script>
{% endblock %}

{% block content %}
<div class="wrapper">
	<div class="accordion_wrap">
		<button class="accordion_header" type="button">My Recent Activity</button>
		<div class="accordion_body">
			<p>Saat ini sedang mencoba hal baru di mata kuliah PPW yaitu javascript dan JQuery
			Semoga bisa memahami dengan baik.</p>
		</div>
	</div>
	<div class="accordion_wrap">
		<button class="accordion_header" type="button">Pengalaman Organisasi/Kepanitiaan</button>
		<div class="accordion_body">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			Anda Membaca Ini Karena Pengalaman Organisasi/Kepanitian.equals(Null) is True.</p>
		</div>
	</div>
	<div class="accordion_wrap">
		<button class="accordion_header" type="button">Prestasi</button>
		<div class="accordion_body">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			Anda Membaca Ini Karena Prestasi.equals(Null) is True.</p>
		</div>
	</div>
	<div class="accordion_wrap">
		<button class="accordion_header" type="button">Hal yang ingin dicapai</button>
		<div class="accordion_body">
			<p>Semoga hal-hal baik masih tersisa.</p>
		</div>
	</div>
</div>
{% endblock %}

myscheduleApp/templates/add.html
{% extends 'base.html'%}

{% block title %}Add New Subject {% endblock %}

{% block content%}
<div class="col-md-12">
	<h4>SUBJECT DATABASE</h4>
	<form method="POST" class="post-form" action="/addnew" autocomplete="off">
		{% csrf_token %}
		<div id = "addcontainer" class="container">
			<br>
			<div class="form-group row">
				<label class="col-sm-1 col-form-label"></label>
				<div class="col-sm-5">
					<h3 class="text text-center display-4">Add New Subject</h3>
				</div>
				
			</div>

			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Mata Kuliah:</label>
				<div class="col-sm-4">
					{{ form.nama_matkul }}
				</div>
				
			</div>

			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Jumlah SKS:</label>
				<div class="col-sm-4">
					{{form.sks}}
				</div>
				
			</div>

			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Term:</label>
				<div class="col-sm-4">
					{{form.term}}
				</div>
				
			</div>
			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Dosen Pengajar:</label>
				<div class="col-sm-4">
					{{form.dosen}}
				</div>
				
			</div>

			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Ruang Kelas:</label>
				<div class="col-sm-4">
					{{form.ruang_kelas}}
				</div>
				
			</div>

			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Deskripsi:</label>
				<div class="col-sm-4">
					{{form.deskripsi}}
				</div>
				
			</div>
			<div class="form-group row">
				<label class="col-sm-1 col-form-label"></label>
				<div class="col-sm-4">
					<button id="addbutton" type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Submit</button>
				</div>
				
			</div>

		</div>
	</form>
</div>

{% endblock %}

myscheduleApp/templates/edit.html
{% extends 'base.html' %}
{% block title %}Edit Data{% endblock title %}
{% block content %}
<div class="col-md-12">
	<form method="POST" class="post-form" action="/update/{{ matkul.id }}" autocomplete="off">
		{% csrf_token %}
		<div class="container">
			<br>
			<div class="form-group row">
				<label class="col-sm-1 col-form-label"></label>
				<div class="col-sm-4">
					<h3>Edit Details</h3>
				</div>
				
			</div>

			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Mata Kuliah:</label>
				<div class="col-sm-4">
					<input type="text" name="nama_matkul" id="id_mata_kuliah" class="form-control" required maxlength="25" value="{{ matkul.nama_matkul}}">
				</div>
				
			</div>

			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Jumlah SKS:</label>
				<div class="col-sm-4">
					<input type="text" name="sks" id="id_sks" class="form-control" required maxlength="25" value="{{ matkul.sks }}">
				</div>
			</div>

			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Term:</label>
				<div class="col-sm-4">
					<input type="text" name="term" id="id_term" class="form-control" required maxlength="25" value="{{ matkul.term }}">
				</div>
				
			</div>
			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Dosen Pengajar:</label>
				<div class="col-sm-4">
					<input type="text" name="dosen" id="id_dosen" class="form-control" required maxlength="25" value="{{ matkul.dosen }}">
				</div>
				
			</div>

			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Ruang Kelas:</label>
				<div class="col-sm-4">
					<input type="text" name="ruang_kelas" id="id_ruang_kelas" class="form-control" required maxlength="25" value="{{ matkul.ruang_kelas }}">
				</div>
				
			</div>

			<div class="form-group row">
				<label class="col-sm-2 col-form-label">Deskripsi</label>
				<div class="col-sm-4">
					<input type="text" name="deskripsi" id="id_deskripsi" class="form-control" required maxlength="25" value="{{ matkul.deskripsi }}">
				</div>
				
			</div>
			<div class="form-group row">
				<label class="col-sm-1 col-form-label"></label>
				<div class="col-sm-4">
					<button type="submit" class="btn btn-primary">Update</button>
				</div>
				
			</div>

		</div>
	</form>
</div>
		
{% endblock %}

myscheduleApp/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}MyDB{% endblock title %}
{% block content %}
	<div class="col-md-12">
		<h4 class="text text-center text-info display-4" >DATA CENTER</h4>
		<div class="table-responsive">
			<table  id="#bootstrapdatatable" class="table table-striped table-dark table-hover table-bordered" data-search = "true" width="100%">
				<thead>
					<th>ID</th>
					<th>Mata Kuliah</th>
					<th>SKS</th>
					<th>Dosen Pengajar</th>
					<th>Term</th>
					<th>Ruang Kelas</th>
					<th>Deskripsi</th>
					<th>Edit</th>
					<th>Delete</th>
				</thead>

				<tbody>
					{% for matkul in matkul %}
						<tr>
							<td>{{ matkul.id }}</td>
							<td><a href="#">{{ matkul.nama_matkul }}</a></td>
							<td>{{ matkul.sks }}</td>
							<td>{{ matkul.dosen }}</td>
							<td>{{ matkul.term }}</td>
							<td>{{ matkul.ruang_kelas }}</td>
							<td>{{ matkul.deskripsi }}</td>
							<td><a href="/edit/{{ matkul.id }}" class="btn btn-primary btn-xs"><span class="fas fa-edit fa-md"></span></a></td>
	     					<td><a href="/delete/{{ matkul.id }}" class="btn btn-danger btn-xs" data-title="Delete" onclick="return confirm('are you sure want to delete {{matkul.nama_matkul}}')"><span class="fas fa-trash fa-sm"></span></a></td>  
						</tr>
					{% endfor %}
				</tbody>
			</table>
			<span><a href="/addnew" class="btn btn-primary bt-lg">Add New Subject</a></span>
		</div>
	</div>
	<div id="actcontainerhome" class="container mt-5">
	<div id ="jumboact" class="jumbotron justify-content-center">
		<h1 id="acttexthome"class="text text-center display-3">My Activity</h1>
		{% if activities.count == 0%}
			<h3 class="text-success">No Activity yet..</h3>
		{% endif %}
		<div id="actcarddeckhome" class="card-deck">
			{% for act in activities %}
				<div id="actcardhome" class="card">
						<div class="card-title">
							<h4 class="text-center">{{ act }}</h4>
						</div>
					<div id="actcardbody" class="card-body">
						<ol>
				{% for person in act.person_set.all %}
							<li class="card-text">{{ person }}</li>	
				{% endfor %}
						</ol>
					</div>
				</div>
				
			{% endfor %}

		</div>
	</div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" width="device-width" initial-scale=1>
	<title>{% block title %}{% endblock %}</title>
	{% load static %}
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
	<!-- <script src="https://kit.fontawesome.com/5bba0521e1.js" crossorigin="anonymous"></script> -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
	<link rel="shortcut icon" href="#" >

	
</head>
<body>
	<!-- NAVIGATION -->
	<nav class="navbar navbar-expand-sm navbar-dark bg-primary sticky-top">
	<div class="container-fluid">
		<a class="navbar-brand" href="/"><i class="fab fa-earlybirds fa-lg" alt="MyDB"><h4>My<b>DB</b></h4></i></span></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul  class="navbar-nav ml-auto">
				<li class="nav-item active">
					<a class="nav-link" href="/"><i class="fas fa-house-user fa-lg"></i></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/activity">Activity</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/accordion">About Me</a>
				</li>

				<li class="nav-item">
					<a class="nav-link" href="/bookslib">Books</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/admin"><i class="fas fa-user-shield"></i></a>
				</li>
			</ul>
		</div>
	</div>
	</nav>
<div class="container">
 <div class="row">
    {% block content %}{% endblock %}
 </div>
</div>
{% block scripts %}{% endblock %}	
<!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
 -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>